#!/bin/bash

# Configuration
MODEL="deutsch-gemma3-ib:latest"
TARGET_DIR="~/deutsch-app/test" # Change this to your specific path if needed

# Recursive loop through subfolders
find "$TARGET_DIR" -type f -name "*.txt" | while read -r file; do
    
    # Skip files already generated by the AI to avoid infinite loops
    if [[ $(basename "$file") == AI_* ]]; then
        continue
    fi

    echo "Processing: $file"

    # Extract directory and filename info
    dir_name=$(dirname "$file")
    base_name=$(basename "$file" .txt)
    
    # Read file content and escape for JSON
    # This uses jq to ensure the text is safely formatted for the API
    content=$(cat "$file" | jq -Rs .)

    # Define the linguistic prompt context
    prompt="Produce a .json file "

    # Call Ollama API
    # We use -s to keep the terminal clean and jq to grab the response field
    response=$(curl -s http://localhost:11434/api/generate -d "{
        \"model\": \"$MODEL\",
        \"prompt\": $content,
        \"system\": \"You are a German linguistic expert. Deine Aufgabe ist es, unstrukturierten Text aus Lehrbuchseiten in präzises JSON zu verwandeln.\",
        \"stream\": false
    }" | jq -r '.response')

    # Save to the new file
    # If your filenames have page numbers like 'page10.txt', this results in 'AI_page10.txt'
    output_file="$dir_name/recon_${base_name}.txt"
    echo "$response" > "$output_file"

    echo "Saved to: $output_file"
done